### ISSUE TITLE
Migrate to pre-commit.ci

### ISSUE THREAD

**Issue by SammyBaek** [SyncM8/syncm8#14]
pre-commit has an automated ci solution: pre-commit.ci which is free to use for public repos.

However, it doesn't download `node_modules` folder, which causes `eslint` check to fail.

Workaround for now consists of downloading it manually in our custom github action `pre-commit.yml`.

Tried to check for existence then download `node_modules` but pre-commi.ci fails with the following error, probably due to docker issue: https://results.pre-commit.ci/run/github/403146594/1631489578.1YiIkibPRT6ytGcmxxznpQ
```
?25hnpm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/eslint/-/eslint-7.32.0.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npm/_logs/2021-09-12T23_33_04_520Z-debug.log
```

**Comment by EpicPi** [comment]
Github actions are free forever as well; for our purposes, the difference in execution time is immaterial.
